//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEngine.CreateAssetMenuAttribute(fileName="OnFloatEvent", menuName="Events/Float Event")]
    public class FloatEvent : lisandroct.EventSystem.Event<float> {
    }
}
