//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEngine.CreateAssetMenuAttribute(fileName="OnVector3Event", menuName="Events/Vector3 Event")]
    public class Vector3Event : lisandroct.EventSystem.Event<UnityEngine.Vector3> {
    }
}
