//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEditor.CustomEditor(typeof(Vector4Event))]
    public class Vector4Inspector : lisandroct.EventSystem.EventInspector<UnityEngine.Vector4, Vector4Test> {
    }
    
    public class Vector4Test : lisandroct.EventSystem.TestObject<UnityEngine.Vector4> {
    }
}
