//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEditor.CustomEditor(typeof(Vector3Event))]
    public class Vector3Inspector : lisandroct.EventSystem.EventInspector<UnityEngine.Vector3, Vector3Test> {
    }
    
    public class Vector3Test : lisandroct.EventSystem.TestObject<UnityEngine.Vector3> {
    }
}
