//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEditor.CustomEditor(typeof(Vector2Event))]
    public class Vector2Inspector : lisandroct.EventSystem.EventInspector<UnityEngine.Vector2, Vector2Test> {
    }
    
    public class Vector2Test : lisandroct.EventSystem.TestObject<UnityEngine.Vector2> {
    }
}
