//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisandroct.EventSystem.Events {
    
    
    [UnityEditor.CustomEditor(typeof(Vector2IntEvent))]
    public class Vector2IntInspector : lisandroct.EventSystem.EventInspector<UnityEngine.Vector2Int, Vector2IntTest> {
    }
    
    public class Vector2IntTest : lisandroct.EventSystem.TestObject<UnityEngine.Vector2Int> {
    }
}
